name = "flashtransfer"
main = "src/worker.ts"
compatibility_date = "2024-04-05"

[vars]
SUPABASE_URL = "https://drfsdvhrbyetqmqxthuu.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyZnNkdmhyYnlldHFtcXh0aHV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwNjIzNzMsImV4cCI6MjA3OTYzODM3M30.QvWNVVDq-UCIjyaJyep84vQs5UaJUNH2mLFFWmiUPos"
